{{- if .Values.backupDaemon.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.name" . }}-backup-daemon-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
    release: {{ .Release.Name }}
    {{- if .Values.backupDaemon.cloudBackuper.backupDaemonCredentials }}
    cloud-backuper.netcracker.com/backup-daemon-credentials: "true"
    {{- end}}
type: Opaque
stringData:
  username: {{ .Values.global.secrets.backupDaemon.username | default "" | quote }}
  password: {{ .Values.global.secrets.backupDaemon.password | default "" | quote }}
{{- end }}