{{- if .Values.cruiseControl.envoyGateway.enabled }}
{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") (eq .Values.PAAS_PLATFORM "KUBERNETES") -}}
{{- if and .Values.cruiseControl.install .Values.cruiseControl.ui.enabled }}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cruise-control-httproute
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
  annotations:
    route.openshift.io/termination: edge
spec:
  parentRefs:
  {{- include "gateway.parentRefs" (list . .Values.cruiseControl.envoyGateway.parentRefs) | nindent 2 }}

  hostnames:
  {{- if .Values.cruiseControl.envoyGateway.host }}
    - {{ .Values.cruiseControl.envoyGateway.host | quote }}
  {{- else }}
    - {{ include "cruise-control.ingressHost" . | quote }}
  {{- end }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ template "kafka.name" . }}-cruise-control
          port: 9090

{{- end }}
{{- end }}
{{- end }}