name: Helm Chart Hardening Check
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  check:
    uses: borislavr/qubership-workflow-hub/.github/workflows/re-helm-hardening.yaml@main
    with:
      chart-path: operator/charts/helm/kafka
