name: Clean old workflow runs
on:
  workflow_dispatch:
    inputs:
      workflow-name:
        description: Name of the workflow or file name
        default: ''
        type: string
        required: true
      retain-days:
        description: How many days to stay
        required: false
        default: 30
      keep-minimum-runs:
        description: Number of runs to keep
        required: false
        default: 10
jobs:
  cleanup-days:
    permissions:
      actions: write
      contents: read
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-workflow-runs-cleaner.yml@feature/old-job-runs-cleaner
    with:
      workflow-name: "${{ inputs.workflow-name }}"
      retain-days: ${{ inputs.retain-days }}"
      keep-minimum-runs: ${{ inputs.keep-minimum-runs }}

