name: Run Hardening Tests

permissions:
  contents: read
  packages: read
  actions: read

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  workflow_dispatch: {}

jobs:
  Hardening-Tests:
    uses: borislavr/qubership-test-pipelines/.github/workflows/kafka.yaml@kafka-hardening-scan
    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: 'kafka-hardening-scan' #this value must match the value after '@' in 'uses'
      skip_tests: false
      scope: 'hardening'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
