name: Run Hardening Tests

permissions:
  contents: read
  packages: read
  actions: read

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  workflow_dispatch:
    inputs:
      tags:
        required: false
        type: string
        default: ""
        description: "Tags"
      dry-run:
        required: true
        type: boolean
        default: false
        description: "Dry run mode"
      replace-symbol:
        required: false
        type: string
        default: "_"
        description: "Symbol to replace in tags"

jobs:
  Wait-for-images:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for dev_build.yml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d  # v2.0.4
        id: wait
        with:
          workflow: dev_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20

  Hardening-Tests:
    needs: Wait-for-images
    uses: Netcracker/qubership-test-pipelines/.github/workflows/kafka.yaml@feature/kafka-hardening-scan
    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: 'feature/kafka-hardening-scan' #this value must match the value after '@' in 'uses'
      skip_tests: false
      scope: 'hardening'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
